/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package venuebookingsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;



/**
 *
 * @author BRANDY
 */
public class UnitRegistration extends javax.swing.JFrame {

    /**
     * Creates new form UnitRegistration
     */
    public UnitRegistration() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cCourse = new javax.swing.JComboBox<>();
        cSem = new javax.swing.JComboBox<>();
        btnsearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jUnits = new javax.swing.JTable();
        jDrop = new javax.swing.JButton();
        btnregister = new javax.swing.JButton();
        LadmNo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cCourse.setBackground(new java.awt.Color(204, 204, 204));
        cCourse.setForeground(new java.awt.Color(0, 0, 0));
        cCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer science", "Nursing", "Education", "Law", "Criminology", "Journalism" }));
        cCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCourseActionPerformed(evt);
            }
        });

        cSem.setBackground(new java.awt.Color(204, 204, 204));
        cSem.setForeground(new java.awt.Color(0, 0, 0));
        cSem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.1", "1.2", "2.1", "2.2", "3.1", "3.2", "4.1", "4.2" }));
        cSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSemActionPerformed(evt);
            }
        });

        btnsearch.setBackground(new java.awt.Color(0, 102, 153));
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        jLabel1.setText("Semester");

        jLabel2.setText("Course");

        jUnits.setBackground(new java.awt.Color(204, 204, 204));
        jUnits.setForeground(new java.awt.Color(0, 0, 0));
        jUnits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Unit", "CourseType", "Semester"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jUnits.setRowHeight(40);
        jScrollPane1.setViewportView(jUnits);

        jDrop.setBackground(new java.awt.Color(0, 102, 153));
        jDrop.setText("Drop");
        jDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDropActionPerformed(evt);
            }
        });

        btnregister.setText("Register Units");
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(LadmNo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cSem, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(262, 262, 262)
                        .addComponent(jDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(btnregister, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(LadmNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnregister, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cSemActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/venue allocation", "brand", "brand@#12");
    String Course=cCourse.getSelectedItem().toString();
    String Semester=cSem.getSelectedItem().toString();

   Statement stm = conn.createStatement();

   String sql="SELECT * FROM courses WHERE CourseType = '"+ Course +"' AND Semester ='"+ Semester +"'";

   //jUnits.getColumnModel().getColumn(3).setCellRenderer(new TableActionCellRender());




    ResultSet rs = stm.executeQuery(sql);
    DefaultTableModel model=(DefaultTableModel)jUnits.getModel();

    cCourse.addItemListener(e -> {
    if (e.getStateChange() == ItemEvent.SELECTED) {
        // Clear table data when combobox selection changes

       model.setRowCount(0);
    }
}


    );
    cSem.addItemListener(e -> {
    if (e.getStateChange() == ItemEvent.SELECTED) {
        // Clear table data when combobox selection changes

       model.setRowCount(0);
    }
}


    );

    while (rs.next()) {
        model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3)});
        // Proceed to next frame or action
    }/* else {
        JOptionPane.showMessageDialog(null, "Username or Password did not Match");
    }*/
    conn.close();
} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
}        // TOD
    }//GEN-LAST:event_btnsearchActionPerformed

    private void jDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDropActionPerformed
        // TODO add your handling code here:
       DefaultTableModel tb1Model= (DefaultTableModel) jUnits.getModel();
        if(jUnits.getSelectedRowCount()==1){
            tb1Model.removeRow(jUnits.getSelectedRow());
            
        }else{
            if(jUnits.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Table is Empty.");
                       
            }else{
                JOptionPane.showMessageDialog(this, "Please select Unit to Drop.");
            }
        }
            
    }//GEN-LAST:event_jDropActionPerformed

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
       
        String AdmNo=LadmNo.getText();
        DefaultTableModel tblmodel=(DefaultTableModel) jUnits.getModel();
       if(tblmodel.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Table is Empty.");
            
        }else{
           String Unit,CourseType,Semester;
           try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/venue allocation", "brand", "brand@#12");
            //String AdmNo=new SDashboard1().LAdmNo.getText();
            //System.out.println(AdmNo);
            
            
            
           for(int i=0;i<tblmodel.getRowCount();i++){
           Unit=tblmodel.getValueAt(i, 0).toString();
           CourseType=tblmodel.getValueAt(i, 1).toString();
           Semester=tblmodel.getValueAt(i, 2).toString();
           
           String sql = "INSERT INTO units_registered (Units, CourseType,AdmNo, Semester) VALUES ('" 
             + Unit + "', '" 
             + CourseType + "', '" 
             + AdmNo + "', '" 
             + Semester + "')";
           Statement stm = conn.createStatement();
           stm.executeUpdate(sql);

           
           
           
           }
            
            JOptionPane.showMessageDialog(null,"Record added successfully");
            tblmodel.setRowCount(0);
            
            

           
           
           

            conn.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }        // TODO add your handl
            /*if(jUnits.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Table is Empty.");
                       
            }else{
                JOptionPane.showMessageDialog(this, "Please select Unit to Drop.");
            }*/
        }
        
        
        
    }//GEN-LAST:event_btnregisterActionPerformed

    private void cCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCourseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnitRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnitRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnitRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnitRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SDashboard1().setVisible(true);
                new UnitRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel LadmNo;
    private javax.swing.JButton btnregister;
    private javax.swing.JButton btnsearch;
    private javax.swing.JComboBox<String> cCourse;
    private javax.swing.JComboBox<String> cSem;
    private javax.swing.JButton jDrop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jUnits;
    // End of variables declaration//GEN-END:variables
}
